server:
  port: 8762

spring:
  application:
    name: service-auth
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/template_cloud?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
     username: test
     password: 123456
     filters: wall,mergeStat

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

mybatis-plus:
  mapperLocations: classpath*:com/shuyu/springcloud/db/**/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl