server:
  port: 8762

spring:
  application:
    name: service-auth
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/template_cloud?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
     username: test
     password: 123456
     filters: wall,mergeStat

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:  # 日志级别
    org.springframework.web: DEBUG # 配置spring web日志级别
    org:
      hibernate:
        SQL: DEBUG