
server:
  port: 8764

spring:
  application:
    name: service-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    user:
      path: /user/**
      serviceId: service-user
    oauth:
      path: /oauth/**
      serviceId: service-auth