server:
  port: 8763

spring:
  application:
    name: service-user
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/template_cloud?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
     username: test
     password: 123456
     filters: wall,mergeStat

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:  # 日志级别
    org.springframework.web: DEBUG # 配置spring web日志级别
    org:
      hibernate:
        SQL: DEBUG

security:
  oauth2:
    resource:
      id: service-user
      #资源服务器配置后，从授权服务器通过token判断用户信息
      user-info-uri: http://localhost:8764/oauth/user/member
      prefer-token-info: false
      #token-info-uri和user-info-uri都配置了，更倾向于用哪个
      #在获得token后，通过userInfoUri里的接口，看看到底有没有返回值，也就是要验证一下token是不是正确的